version: '3.8'
services:
  tor:
    container_name: tor
    image: lncm/tor:0.4.6.8@sha256:c262923ffd0bd224a4a4123cf1c88eea11e2314566b7b7e8a1f77969deeb0208
    user: toruser
    restart: on-failure
    volumes:
    - ${PWD}/tor/torrc-core:/etc/tor/torrc
    - ${PWD}/tor/data:/var/lib/tor/
    ports:
    - 127.0.0.1:$TOR_PROXY_PORT:$TOR_PROXY_PORT
    networks:
      default:
        ipv4_address: $TOR_PROXY_IP
  app-tor:
    container_name: app-tor
    image: lncm/tor:0.4.6.8@sha256:c262923ffd0bd224a4a4123cf1c88eea11e2314566b7b7e8a1f77969deeb0208
    user: toruser
    restart: on-failure
    volumes:
    - ${PWD}/tor/torrc-apps:/etc/tor/torrc
    - ${PWD}/tor/data:/var/lib/tor/
    networks:
      default:
        ipv4_address: $APPS_TOR_IP
  app-2-tor:
    container_name: app-2-tor
    image: lncm/tor:0.4.6.8@sha256:c262923ffd0bd224a4a4123cf1c88eea11e2314566b7b7e8a1f77969deeb0208
    user: toruser
    restart: on-failure
    volumes:
    - ${PWD}/tor/torrc-apps-2:/etc/tor/torrc
    - ${PWD}/tor/data:/var/lib/tor/
    networks:
      default:
        ipv4_address: $APPS_2_TOR_IP
  app-3-tor:
    container_name: app-3-tor
    image: lncm/tor:0.4.6.8@sha256:c262923ffd0bd224a4a4123cf1c88eea11e2314566b7b7e8a1f77969deeb0208
    user: toruser
    restart: on-failure
    volumes:
    - ${PWD}/tor/torrc-apps-3:/etc/tor/torrc
    - ${PWD}/tor/data:/var/lib/tor/
    networks:
      default:
        ipv4_address: $APPS_3_TOR_IP
  nginx:
    container_name: nginx
    image: nginx:1.21.6@sha256:2834dc507516af02784808c5f48b7cbe38b8ed5d0f4837f16e78d00deb7e7767
    depends_on:
    - dashboard
    - manager
    volumes:
    - ${PWD}/nginx:/etc/nginx
    restart: on-failure
    stop_grace_period: 30s
    ports:
    - ${NGINX_PORT}:80
    - 433:433
    - ${NGINX_SSL_PORT}:443
    networks:
      default:
        ipv4_address: $NGINX_IP
  bitcoin:
    container_name: bitcoin
    image: nolim1t/bitcoinknots:v22.0.knots20211108@sha256:a475da2b2ecda55fcc65ea23e1a36c58b2c10549f1c3d3bb3c31c7dda1127354
    depends_on:
    - tor
    volumes:
    - ${PWD}/bitcoin:/data/.bitcoin
    restart: on-failure
    stop_grace_period: 1m
    ports:
    - $BITCOIN_P2P_PORT:$BITCOIN_P2P_PORT
    networks:
      default:
        ipv4_address: $BITCOIN_IP
  lightning:
    container_name: lightning
    image: lightninglabs/lnd:v0.14.2-beta@sha256:8318a24a3ad7319e424253eb56efcbf38e820ebc6d6b6edeec6a8a4e3e9314a0
    user: 1000:1000
    depends_on:
    - tor
    - bitcoin
    volumes:
    - ${PWD}/lnd:/data/.lnd
    - ${PWD}/walletpassword:/walletpassword
    environment:
      HOME: /data
    restart: on-failure
    stop_grace_period: 5m30s
    ports:
    - 9735:9735
    - $LND_REST_PORT:$LND_REST_PORT
    - $LND_GRPC_PORT:$LND_GRPC_PORT
    networks:
      default:
        ipv4_address: $LND_IP
  dashboard:
    container_name: dashboard
    image: ghcr.io/runcitadel/dashboard:v0.0.9@sha256:d5e523e0640daca7c75084e692bb8e91a8892666d6215af0111e174b285e72b6
    restart: on-failure
    stop_grace_period: 1m30s
    networks:
      default:
        ipv4_address: $DASHBOARD_IP
  manager:
    container_name: manager
    image: ghcr.io/runcitadel/manager:v0.0.10@sha256:29b513831e8a48f9726b3b66be1a9d80e1e11acc9d384475d55adccb3c2faad3
    depends_on:
    - tor
    - redis
    command:
    - ./start.sh
    restart: on-failure
    init: true
    stop_grace_period: 5m30s
    volumes:
    - ${PWD}/info.json:/info.json
    - ${PWD}/db:/db
    - ${PWD}/events/signals:/signals
    - ${PWD}/apps:/apps
    - ${PWD}/lnd:/lnd:ro
    - ${PWD}/statuses:/statuses
    - ${PWD}/tor/data:/var/lib/tor/
    - jwt-public-key:/jwt-public-key
    - jwt-private-key:/jwt-private-key
    environment:
      PORT: '3006'
      USER_PASSWORD_FILE: /db/user.json
      JWT_PUBLIC_KEY_FILE: /jwt-public-key/jwt.pem
      JWT_PRIVATE_KEY_FILE: /jwt-private-key/jwt.key
      JWT_EXPIRATION: '3600'
      DEVICE_HOSTS: ${DEVICE_HOSTS:-"http://citadel.local"}
      DEVICE_HOSTNAME: ${DEVICE_HOSTNAME:-""}
      MIDDLEWARE_API_URL: http://$MIDDLEWARE_IP
      SEED_FILE: /db/citadel-seed/seed
      BITCOIN_P2P_PORT: $BITCOIN_P2P_PORT
      BITCOIN_RPC_PORT: $BITCOIN_RPC_PORT
      BITCOIN_RPC_USER: $BITCOIN_RPC_USER
      BITCOIN_RPC_PASSWORD: $BITCOIN_RPC_PASS
      LND_CERT_FILE: /lnd/tls.cert
      LND_ADMIN_MACAROON_FILE: /lnd/data/chain/bitcoin/${BITCOIN_NETWORK}/admin.macaroon
      GITHUB_REPO: runcitadel/core
      GITHUB_BRANCH: ${UPDATE_CHANNEL:-"stable"}
      VERSION_FILE: /info.json
      UPDATE_LOCK_FILE: /statuses/update-in-progress
      BACKUP_STATUS_FILE: /statuses/backup-status.json
      DEBUG_STATUS_FILE: /statuses/debug-status.json
      TOR_PROXY_IP: ${TOR_PROXY_IP}
      TOR_PROXY_PORT: ${TOR_PROXY_PORT}
      TOR_HIDDEN_SERVICE_DIR: /var/lib/tor
      IS_CITADEL_OS: ${IS_CITADEL_OS:-"true"}
      REDIS_PASSWORD: freedom
      REDIS_IP: $REDIS_IP
      REDIS_PORT: 6379
      UNSAFE_REMOVE_CORS_CHECK: true
    networks:
      default:
        ipv4_address: $MANAGER_IP
  middleware:
    container_name: middleware
    image: ghcr.io/runcitadel/middleware:v0.0.8@sha256:f1e400cc4544a1c2a337f4a957693b328c6ee096bff8c06f0cdfb2eabcb2f4aa
    depends_on:
    - manager
    - bitcoin
    - lightning
    - redis
    - c-lightning
    command: sh -c "./wait-for-manager.sh $MANAGER_IP && ./start.sh"
    restart: on-failure
    volumes:
    - ${PWD}/lnd:/lnd
    - ${PWD}/c-lightning:/c-lightning
    - jwt-public-key:/jwt-public-key
    environment:
      PORT: '3005'
      BITCOIN_HOST: $BITCOIN_IP
      RPC_PORT: $BITCOIN_RPC_PORT
      RPC_USER: $BITCOIN_RPC_USER
      RPC_PASSWORD: $BITCOIN_RPC_PASS
      LND_NETWORK: $BITCOIN_NETWORK
      LND_HOST: ${LND_IP}
      JWT_PUBLIC_KEY_FILE: /jwt-public-key/jwt.pem
      DEVICE_HOSTS: ${DEVICE_HOSTS:-"http://citadel.local"}
      UNSAFE_REMOVE_CORS_CHECK: true
      LIGHTNING_IMPL: c-lightning
    networks:
      default:
        ipv4_address: $MIDDLEWARE_IP
  neutrino-switcher:
    container_name: neutrino-switcher
    image: lncm/neutrino-switcher:1.0.5@sha256:3ddf58c5599ba22db8414f2694bfeeba086455d4a19b4955b26c3ae5e967d42a
    depends_on:
    - bitcoin
    - lightning
    restart: on-failure
    volumes:
    - ${PWD}/lnd:/lnd
    - ${PWD}/statuses:/statuses
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
      JSONRPCURL: http://${BITCOIN_IP}:${BITCOIN_RPC_PORT}
      RPCUSER: $BITCOIN_RPC_USER
      RPCPASS: $BITCOIN_RPC_PASS
      LND_CONTAINER_NAME: lightning
      SLEEPTIME: 3600
    networks:
      default:
        ipv4_address: $NEUTRINO_SWITCHER_IP
  electrum:
    container_name: electrum
    image: ghcr.io/runcitadel/electrs:v0.9.5@sha256:5fdd76415645de14f31c43844dc143b1477f86872d2f73a041c5005d469ed510
    working_dir: /data
    volumes:
    - ${PWD}/bitcoin:/bitcoin:ro
    - ${PWD}/electrs:/data
    restart: on-failure
    stop_grace_period: 5m
    ports:
    - $ELECTRUM_PORT:$ELECTRUM_PORT
    networks:
      default:
        ipv4_address: $ELECTRUM_IP
  c-lightning:
    container_name: c-lightning
    image: ghcr.io/runcitadel/c-lightning:main@sha256:69c2870f627fccd5df5b5df24f2e239c5309c444cf35d103969031e461509174
    environment:
      LIGHTNINGD_NETWORK: bitcoin
      CL_REST_STATE_DIR: /data/.lightning
    restart: on-failure
    volumes:
    - ${PWD}/c-lightning:/data/.lightning
    - ${PWD}/bitcoin:/data/.bitcoin
    ports:
    - $SPARKO_RPC_PORT:$SPARKO_RPC_PORT
    networks:
      default:
        ipv4_address: $C_LIGHTNING_IP
  redis:
    container_name: redis
    image: redis:6.2.6-bullseye@sha256:0d9c9aed1eb385336db0bc9b976b6b49774aee3d2b9c2788a0d0d9e239986cb3
    working_dir: /data
    volumes:
    - ${PWD}/redis:/data
    command: redis-server --requirepass freedom
    restart: on-failure
    stop_grace_period: 1m
    init: true
    networks:
      default:
        ipv4_address: $REDIS_IP
networks:
  default:
    name: citadel_main_network
    ipam:
      driver: default
      config:
      - subnet: $NETWORK_IP/24
volumes:
  jwt-public-key: null
  jwt-private-key: null
