# SPDX-FileCopyrightText: 2020 Umbrel. https://getumbrel.com
# SPDX-FileCopyrightText: 2021-2022 Citadel and contributors.
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Please note: This file can't be changed, any changes will be overwritten the next time you start Citadel.

log_filters = "INFO"
network = "<bitcoin-network-electrs>"
db_dir = "/data/db"
daemon_dir = "/bitcoin"
daemon_rpc_addr = "<bitcoin-ip>:<bitcoin-rpc-port>"
daemon_p2p_addr = "<bitcoin-ip>:<bitcoin-p2p-port>"
electrum_rpc_addr = "0.0.0.0:<electrum-port>"
server_banner = "Citadel v<citadel-version>"
